"""Simplify internal transaction type to TRANSFER

Revision ID: 0386ab5f160f
Revises: 27796eac7d34
Create Date: 2026-06-27 17:52:12.069838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0386ab5f160f'
down_revision: Union[str, Sequence[str], None] = '27796eac7d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
