"""remove pairing code rotation

Revision ID: 3b72d8c81ea5
Revises: 8d731d284a93
Create Date: 2026-06-16 15:01:13.842732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b72d8c81ea5'
down_revision: Union[str, Sequence[str], None] = '8d731d284a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pairing_codes_used_by_fkey'), 'pairing_codes', type_='foreignkey')
    op.drop_column('pairing_codes', 'used_by')
    op.drop_column('pairing_codes', 'is_used')
    op.drop_column('pairing_codes', 'expires_at')
    op.drop_column('pairing_codes', 'used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing_codes', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('pairing_codes', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pairing_codes', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('pairing_codes', sa.Column('used_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pairing_codes_used_by_fkey'), 'pairing_codes', 'users', ['used_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
