"""add purpose column to email_verifications

Revision ID: 8f2cdc42f436
Revises: 692749f513b2
Create Date: 2026-06-22 18:20:41.630600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2cdc42f436'
down_revision: Union[str, Sequence[str], None] = '692749f513b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable
    op.add_column('email_verifications', sa.Column('purpose', sa.String(), nullable=True))
    
    # Backfill existing data
    op.execute("UPDATE email_verifications SET purpose = 'email_verification'")
    
    # Alter column to be non-nullable
    op.alter_column('email_verifications', 'purpose', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verifications', 'purpose')
    # ### end Alembic commands ###
