"""add_performance_indexes

Revision ID: 9b22cde1a78c
Revises: 627db8be1dbd
Create Date: 2026-07-06 13:46:49.990115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b22cde1a78c'
down_revision: Union[str, Sequence[str], None] = '627db8be1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assets_family', 'assets', ['family_id'], unique=False)
    op.create_index('ix_budgets_family_month_year', 'budgets', ['family_id', 'month', 'year'], unique=False)
    op.create_index('ix_transactions_family_date', 'transactions', ['family_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_family_date', table_name='transactions')
    op.drop_index('ix_budgets_family_month_year', table_name='budgets')
    op.drop_index('ix_assets_family', table_name='assets')
    # ### end Alembic commands ###
