"""Add used_by and used_at to pairing_codes

Revision ID: f4a01934d3f4
Revises: 9d7ce287aaaf
Create Date: 2026-06-13 18:06:33.043292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a01934d3f4'
down_revision: Union[str, Sequence[str], None] = '9d7ce287aaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing_codes', sa.Column('used_by', sa.UUID(), nullable=True))
    op.add_column('pairing_codes', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'pairing_codes', 'users', ['used_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairing_codes', type_='foreignkey')
    op.drop_column('pairing_codes', 'used_at')
    op.drop_column('pairing_codes', 'used_by')
    # ### end Alembic commands ###
